//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCESSTIMECOUNT
    {
        public int ID { get; set; }
        public System.DateTime DATE { get; set; }
        public int ACCESSTIME { get; set; }
    }
}
