//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBER
    {
        public int ID { get; set; }
        public Nullable<int> MEMBERCATEGORYID { get; set; }
        public string FULLNAME { get; set; }
        public Nullable<int> PHONENUMBER { get; set; }
        public string PASSWORD { get; set; }
        public string EMAIL { get; set; }
        public Nullable<bool> EMAILCONFIGMER { get; set; }
        public string CAPCHA { get; set; }
        public string ADDRESS { get; set; }
    
        public virtual MEMBERCATOGERY MEMBERCATOGERY { get; set; }
    }
}
