//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODER
    {
        public int ID { get; set; }
        public Nullable<int> CUSTOMERID { get; set; }
        public Nullable<System.DateTime> DATAODER { get; set; }
        public Nullable<System.DateTime> DATASHIP { get; set; }
        public Nullable<bool> OFFER { get; set; }
        public Nullable<bool> ISPAID { get; set; }
        public Nullable<bool> ISCANCEL { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    }
}
