//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTCATOGERY
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string IMAGE { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDATE { get; set; }
        public Nullable<int> GENDERID { get; set; }
        public Nullable<int> SUBCATEGORYID { get; set; }
    
        public virtual GENDER GENDER { get; set; }
        public virtual SUBCATEGORY SUBCATEGORY { get; set; }
    }
}
