//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> TRADEMARKID { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string IMAGE1 { get; set; }
        public string IMAGE2 { get; set; }
        public string IMAGE3 { get; set; }
        public string IMAGE4 { get; set; }
        public Nullable<int> CATEGORYID { get; set; }
        public Nullable<decimal> PROMOTIONPRICE { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<bool> HOMEFLAG { get; set; }
        public Nullable<bool> HOTFLAG { get; set; }
        public Nullable<int> VIEWCOUNT { get; set; }
        public Nullable<int> COMMENTCOUNT { get; set; }
        public Nullable<int> PURCHASECOUNT { get; set; }
        public string ISNEW { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDATE { get; set; }
        public Nullable<int> GENDERID { get; set; }
        public string MOREINFORMATION { get; set; }
        public string WARRANTYINFORMATION { get; set; }
        public Nullable<int> DISCOUNT { get; set; }
        public Nullable<int> CARTID { get; set; }
    
        public virtual CART CART { get; set; }
        public virtual GENDER GENDER { get; set; }
        public virtual TRADEMARK TRADEMARK { get; set; }
    }
}
