//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionWebsite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebShoseEntities : DbContext
    {
        public WebShoseEntities()
            : base("name=WebShoseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCESSTIMECOUNT> ACCESSTIMECOUNTs { get; set; }
        public virtual DbSet<CART> CARTs { get; set; }
        public virtual DbSet<COLOR> COLORs { get; set; }
        public virtual DbSet<COLORPRODUCT> COLORPRODUCTs { get; set; }
        public virtual DbSet<EMLOYEE> EMLOYEEs { get; set; }
        public virtual DbSet<EMLOYEETYPE> EMLOYEETYPEs { get; set; }
        public virtual DbSet<GENDER> GENDERs { get; set; }
        public virtual DbSet<MEMBER> MEMBERs { get; set; }
        public virtual DbSet<MEMBERCATOGERY> MEMBERCATOGERies { get; set; }
        public virtual DbSet<ODER> ODERs { get; set; }
        public virtual DbSet<ODERDETAIL> ODERDETAILs { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTs { get; set; }
        public virtual DbSet<PRODUCTCATOGERY> PRODUCTCATOGERies { get; set; }
        public virtual DbSet<SIZEPRODUCT> SIZEPRODUCTs { get; set; }
        public virtual DbSet<SUBCATEGORY> SUBCATEGORies { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TRADEMARK> TRADEMARKs { get; set; }
    }
}
